### ISSUE TITLE
Inconsistent cert verification errors returned between TLS 1.2 and 1.3

### ISSUE THREAD

**Issue by c29reid** [libressl-portable/openbsd#122] opened 2021-03-30 19:19 UTC
I originally reported this in https://github.com/curl/curl/issues/6790#issuecomment-810448703.

I was seeing this when trying to connect to a local site with self generated certs on curl + libressl + TLS 1.3.
libressl with TLS 1.3 returns different errors than libressl + TLS 1.2 or OpenSSL + TLS 1.3 when connecting to a site that fails cert verification.
With libressl + TLS 1.2 or OpenSSL + TLS 1.3, a failed cert verification results only in `SSL_R_CERTIFICATE_VERIFY_FAILED` pushed to the error list.
With libressl + TLS 1.3 `SSL_R_TLSV1_ALERT_UNKNOWN_CA` is first pushed from [here](https://github.com/openbsd/src/blob/master/lib/libssl/tls13_lib.c#L150) and then `SSL_R_CERTIFICATE_VERIFY_FAILED` is pushed after.

```
$ curl https://localhost:443 --verbose --tlsv1.3
*   Trying 127.0.0.1:443...
* Connected to localhost (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
Client sending ClientHello
Client receiving ServerHello
Client recv returned -3
Client receiving ServerHello
Client receiving EncryptedExtensions
Client receiving CertificateRequest
* error:1404B418:SSL routines:ST_CONNECT:tlsv1 alert unknown ca
* Closing connection 0
curl: (35) error:1404B418:SSL routines:ST_CONNECT:tlsv1 alert unknown ca

$ curl https://localhost:443 --verbose --tls-max 1.2
*   Trying 127.0.0.1:443...
* Connected to localhost (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
Client sending ClientHello
Client receiving ServerHello
Client recv returned -3
Client receiving ServerHello
Client recv returned -6
* SSL certificate problem: self signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

I'm not sure if this error change is intended or not.
I wasn't able to clearly tell from the spec and unknown_ca is marked as a fatal_error in both TLS 1.2 and 1.3.

**Comment by c29reid** [comment] 2021-03-31 02:24
Is the call to `SSLerror(ctx->ssl, SSL_AD_REASON_OFFSET + alert_desc);` in `tls13_alert_sent_cb` a copy/paste error from `tls13_alert_received_cb` in https://github.com/libressl-portable/openbsd/blob/master/src/lib/libssl/tls13_lib.c#L150?

I'm not familiar with libressl source but it seems like the only other places that throws SSLError with `SSL_AD_REASON_OFFSET + alert_desc` is when the client receives a fatal alert, not sends.

**Comment by donny-dont** [comment] 2021-04-06 20:23
Hey @busterb my co-worked found this issue and we're not sure if this is the place for getting this resolved. Any assistance would be appreciated.

**Comment by busterb** [comment] 2021-04-07 02:05
Hi @donny-dont, thanks for the note. I think this is an issue with the upstream OpenBSD source, but we're looking into making the error handling uniform in this case.

**Comment by botovq** [comment] 2021-04-07 22:40
> Is the call to SSLerror(ctx->ssl, SSL_AD_REASON_OFFSET + alert_desc); in tls13_alert_sent_cb a copy/paste error from tls13_alert_received_cb in https://github.com/libressl-portable/openbsd/blob/master/src/lib/libssl/tls13_lib.c#L150?

Thanks for the report and for pointing at this. This is indeed the place that causes the problems with curl. It's not a copy-paste error, though. It was added as a cosmetic change with the goal of avoiding `SSL_R_UNKNOWN` errors in some circumstances.

The issue is that curl only inspects the top-most error which will currently be the alert's description obtained from this `SSLerror` call  instead of the  expected `SSL_R_CERTIFICATE_VERIFY_FAILED`. The fix that I have pushed to OpenBSD is to avoid the call if we have already set an error prior to sending the alert:

```diff
        /* All other alerts are treated as fatal in TLSv1.3. */
-       SSLerror(ctx->ssl, SSL_AD_REASON_OFFSET + alert_desc);
+       if (ctx->error.code == 0)
+               SSLerror(ctx->ssl, SSL_AD_REASON_OFFSET + alert_desc);
```

The commit will be synced here soon and will be part of the next release.

**Comment by c29reid** [comment] 2021-04-07 23:58
Great, thanks for taking a look into it! 

Is there an idea on how long until the next release will be out?

**Comment by 4a6f656c** [comment] 2021-04-19 09:20
A development release (3.3.2) is available with this fix - the next stable release is likely a few weeks away.

**Closed by 4a6f656c** 2021-04-19 09:20 UTC
